[tool.ruff]
# Same as Black.
line-length = 127
# Assume Python 3.9
target-version = "py39"
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF"]
# Ignore explicit stacklevel`
ignore = ["B028"]

[tool.ruff.per-file-ignores]
# "./rl_zoo3/plots/all_plots.py"= ["E501"]


[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 127

[tool.isort]
profile = "black"
line_length = 127
src_paths = []


[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
# exclude = """(?x)(
#     rl_zoo3/hyperparams_opt.py$
#     | rl_zoo3/exp_manager.py$
#     | tests/dummy_env/*$
#   )"""
